window.screenOrientation="sensor_landscape",
loadLib("libs/laya.core.js"),
loadLib("libs/laya.ui.js"),
loadLib("libs/laya.d3.js"),
loadLib("adapter/zs.laya.base.js"),
loadLib("adapter/zs.laya.js"),
loadLib("adapter/zs.laya.sdk.js"),
loadLib("adapter/zs.laya.platform.js"),
loadLib("js/bundle.js");